# See the BukkitDev page for config explanation
# MySQL address (leave trailing slash)
host: "http://mysql2.000webhost.com"
# Database to use
database: "a4849714_mine"
# Username for MySQL
user: "a4849714_mine"
# Password for MySQL
password: "ferreira94mine"
# Prefix for table names in database
table_prefix: "ra_"
# Name of the user table
userdb_name: "a4849714_mine"
# Name of the locations table
locationdb_name: "a4849714_mine"
# Commands to allow when not logged in
allowed_commands: ["/login", "/l", "/register"]
# Disable plugin if online-mode is true?
disable_if_online: false
# Encryption type (RAUTH, SHA-512, SHA-256, MD5, etc - any type supported by Java)
encryption_type: "RAUTH"

# Sessions for login
sessions:
  # Enable sessions?
  enabled: true
  # Length in minutes
  length: 10
  # Expand session when you log out? Sessions are started when you first execute /login correctly
  # If this is true, your session is started again when you log out. Example:
  # false: You log in and play for 5 minutes (length is set to 10), and then you log out. When you log back in
  # it verifies you by session. You play for 6 more, and you log back out. When you log back in, you
  # must enter your password.
  #
  # true: You log in and play for 11 minutes. You log out. You join after 5 minutes. It verifies you by
  # session. You play for 20 minutes and log out. You join again after 11 minutes. You must enter your
  # password.
  expand_session_on_quit: true